python -m scripts.train_no_validation --dataset CIFAR10 --algorithm ERM_DataAug --output_dir train-output-ERM_DataAug-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-ERM_DataAug-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm ERM_DataAug --output_dir train-output-ERM_DataAug-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-ERM_DataAug-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm RandSmoothingCVaR_SGD --output_dir train-output-RandSmoothingCVaR_SGD-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-RandSmoothingCVaR_SGD-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm RandSmoothingCVaR_SGD --output_dir train-output-RandSmoothingCVaR_SGD-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-RandSmoothingCVaR_SGD-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm RandSmoothingCVaR_SGD --output_dir train-output-RandSmoothingCVaR_SGD-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-RandSmoothingCVaR_SGD-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm TRADES --output_dir train-output-TRADES-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TRADES-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm TRADES --output_dir train-output-TRADES-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TRADES-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm TRADES --output_dir train-output-TRADES-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TRADES-SVHN >> results.txt;