
python -m scripts.train_no_validation --dataset MNIST --algorithm ERM --output_dir train-output-ERM-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-ERM-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm ERM --output_dir train-output-ERM-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-ERM-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm ERM --output_dir train-output-ERM-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-ERM-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm ERM_DataAug --output_dir train-output-ERM_DataAug-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-ERM_DataAug-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm ERM_DataAug --output_dir train-output-ERM_DataAug-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-ERM_DataAug-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm ERM_DataAug --output_dir train-output-ERM_DataAug-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-ERM_DataAug-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm TRADES --output_dir train-output-TRADES-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TRADES-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm TRADES --output_dir train-output-TRADES-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TRADES-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm TRADES --output_dir train-output-TRADES-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TRADES-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm MARTPGD --output_dir train-output-MARTPGD-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-MARTPGD-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm MARTPGD --output_dir train-output-MARTPGD-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-MARTPGD-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm MARTPGD --output_dir train-output-MARTPGD-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-MARTPGD-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm CVaR_Exact --output_dir train-output-CVaR_Exact-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-CVaR_Exact-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm CVaR_Exact --output_dir train-output-CVaR_Exact-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-CVaR_Exact-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm CVaR_Exact --output_dir train-output-CVaR_Exact-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-CVaR_Exact-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm TERM --output_dir train-output-TERM-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TERM-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm TERM --output_dir train-output-TERM-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TERM-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm TERM --output_dir train-output-TERM-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-TERM-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm FGSM --output_dir train-output-FGSM-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-FGSM-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm FGSM --output_dir train-output-FGSM-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-FGSM-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm FGSM --output_dir train-output-FGSM-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-FGSM-CIFAR10 >> results.txt;
python -m scripts.train_no_validation --dataset MNIST --algorithm KL_DALE_PD --output_dir train-output-KL_DALE_PD-MNIST --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-KL_DALE_PD-MNIST >> results.txt;
python -m scripts.train_no_validation --dataset SVHN --algorithm KL_DALE_PD --output_dir train-output-KL_DALE_PD-SVHN --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-KL_DALE_PD-SVHN >> results.txt;
python -m scripts.train_no_validation --dataset CIFAR10 --algorithm KL_DALE_PD --output_dir train-output-KL_DALE_PD-CIFAR10 --test_attacks PGD_Linf;
python -m scripts.collect_results --depth 0 --input_dir train-output-KL_DALE_PD-CIFAR10 >> results.txt;
